apiVersion: v1
kind: Service
metadata:
  name: {{ include "synthetic.fullname" . }}
  labels:
    {{- include "synthetic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "synthetic.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    {{- if .Values.adapters.grpc }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      appProtocol: grpc
    {{- end }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "synthetic.fullname" . }}
  labels:
    {{- include "synthetic.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "synthetic.fullname" . }}
                port:
                  number: {{ .Values.service.httpPort }}
{{- end }}
