// Integration Hub — worker contract.
//
// One RPC, deliberately. The orchestrator owns credentials, the retry loop, and run
// history; the worker owns the upstream call, the transform, and error *classification*.
// See docs/SPEC.md §4.1 and docs/adr/0003 for why the retry split is where it is.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_REST                 Protocol = 1
	Protocol_GRAPHQL              Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "REST",
		2: "GRAPHQL",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"REST":                 1,
		"GRAPHQL":              2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type Emit int32

const (
	Emit_EMIT_UNSPECIFIED Emit = 0
	Emit_SINGLE           Emit = 1
	Emit_LIST             Emit = 2
)

// Enum value maps for Emit.
var (
	Emit_name = map[int32]string{
		0: "EMIT_UNSPECIFIED",
		1: "SINGLE",
		2: "LIST",
	}
	Emit_value = map[string]int32{
		"EMIT_UNSPECIFIED": 0,
		"SINGLE":           1,
		"LIST":             2,
	}
)

func (x Emit) Enum() *Emit {
	p := new(Emit)
	*p = x
	return p
}

func (x Emit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Emit) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[1].Descriptor()
}

func (Emit) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[1]
}

func (x Emit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Emit.Descriptor instead.
func (Emit) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	IntegrationId string                 `protobuf:"bytes,2,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Protocol      Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=integrationhub.worker.v1.Protocol" json:"protocol,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// REST (protocol = REST)
	Method string            `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"` // GET | POST | ...
	Path   string            `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`     // path params already substituted
	Query  map[string]string `protobuf:"bytes,8,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// GraphQL (protocol = GRAPHQL)
	GraphqlQuery  string `protobuf:"bytes,9,opt,name=graphql_query,json=graphqlQuery,proto3" json:"graphql_query,omitempty"`
	VariablesJson string `protobuf:"bytes,10,opt,name=variables_json,json=variablesJson,proto3" json:"variables_json,omitempty"`
	// Resolved auth headers are included here, scoped to this one invocation.
	// The worker never sees the credential store. Never log this map.
	Headers       map[string]string `protobuf:"bytes,11,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Transform     string            `protobuf:"bytes,12,opt,name=transform,proto3" json:"transform,omitempty"` // JMESPath, evaluated against the decoded body
	Emit          Emit              `protobuf:"varint,13,opt,name=emit,proto3,enum=integrationhub.worker.v1.Emit" json:"emit,omitempty"`
	TimeoutMs     int32             `protobuf:"varint,14,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Attempt       int32             `protobuf:"varint,15,opt,name=attempt,proto3" json:"attempt,omitempty"` // 1-based; for logs/traces only, not control flow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InvokeRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *InvokeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *InvokeRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *InvokeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvokeRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *InvokeRequest) GetGraphqlQuery() string {
	if x != nil {
		return x.GraphqlQuery
	}
	return ""
}

func (x *InvokeRequest) GetVariablesJson() string {
	if x != nil {
		return x.VariablesJson
	}
	return ""
}

func (x *InvokeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRequest) GetTransform() string {
	if x != nil {
		return x.Transform
	}
	return ""
}

func (x *InvokeRequest) GetEmit() Emit {
	if x != nil {
		return x.Emit
	}
	return Emit_EMIT_UNSPECIFIED
}

func (x *InvokeRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *InvokeRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type InvokeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ok                 bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UpstreamStatus     int32                  `protobuf:"varint,2,opt,name=upstream_status,json=upstreamStatus,proto3" json:"upstream_status,omitempty"`
	RecordsJson        []byte                 `protobuf:"bytes,3,opt,name=records_json,json=recordsJson,proto3" json:"records_json,omitempty"` // canonical records array, UTF-8 JSON
	Count              int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	UpstreamDurationMs int32                  `protobuf:"varint,5,opt,name=upstream_duration_ms,json=upstreamDurationMs,proto3" json:"upstream_duration_ms,omitempty"`
	// UPSTREAM_5XX | UPSTREAM_4XX | TIMEOUT | CONNECT | TRANSFORM | GRAPHQL_ERROR | RATE_LIMITED
	ErrorCode     string `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // must never contain header or credential values
	Retryable     bool   `protobuf:"varint,8,opt,name=retryable,proto3" json:"retryable,omitempty"`                          // the worker classifies; the orchestrator decides
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InvokeResponse) GetUpstreamStatus() int32 {
	if x != nil {
		return x.UpstreamStatus
	}
	return 0
}

func (x *InvokeResponse) GetRecordsJson() []byte {
	if x != nil {
		return x.RecordsJson
	}
	return nil
}

func (x *InvokeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InvokeResponse) GetUpstreamDurationMs() int32 {
	if x != nil {
		return x.UpstreamDurationMs
	}
	return 0
}

func (x *InvokeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *InvokeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InvokeResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x18integrationhub.worker.v1\"\xd7\x05\n" +
	"\rInvokeRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12%\n" +
	"\x0eintegration_id\x18\x02 \x01(\tR\rintegrationId\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12>\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\".integrationhub.worker.v1.ProtocolR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12H\n" +
	"\x05query\x18\b \x03(\v22.integrationhub.worker.v1.InvokeRequest.QueryEntryR\x05query\x12#\n" +
	"\rgraphql_query\x18\t \x01(\tR\fgraphqlQuery\x12%\n" +
	"\x0evariables_json\x18\n" +
	" \x01(\tR\rvariablesJson\x12N\n" +
	"\aheaders\x18\v \x03(\v24.integrationhub.worker.v1.InvokeRequest.HeadersEntryR\aheaders\x12\x1c\n" +
	"\ttransform\x18\f \x01(\tR\ttransform\x122\n" +
	"\x04emit\x18\r \x01(\x0e2\x1e.integrationhub.worker.v1.EmitR\x04emit\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x0e \x01(\x05R\ttimeoutMs\x12\x18\n" +
	"\aattempt\x18\x0f \x01(\x05R\aattempt\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\x0eInvokeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0fupstream_status\x18\x02 \x01(\x05R\x0eupstreamStatus\x12!\n" +
	"\frecords_json\x18\x03 \x01(\fR\vrecordsJson\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x120\n" +
	"\x14upstream_duration_ms\x18\x05 \x01(\x05R\x12upstreamDurationMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tretryable\x18\b \x01(\bR\tretryable*;\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04REST\x10\x01\x12\v\n" +
	"\aGRAPHQL\x10\x02*2\n" +
	"\x04Emit\x12\x14\n" +
	"\x10EMIT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x01\x12\b\n" +
	"\x04LIST\x10\x022e\n" +
	"\x06Worker\x12[\n" +
	"\x06Invoke\x12'.integrationhub.worker.v1.InvokeRequest\x1a(.integrationhub.worker.v1.InvokeResponseBaZDgithub.com/evanpthompson/integration-hub/synthetic/workerv1;workerv1\xaa\x02\x18IntegrationHub.Worker.V1b\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_worker_proto_goTypes = []any{
	(Protocol)(0),          // 0: integrationhub.worker.v1.Protocol
	(Emit)(0),              // 1: integrationhub.worker.v1.Emit
	(*InvokeRequest)(nil),  // 2: integrationhub.worker.v1.InvokeRequest
	(*InvokeResponse)(nil), // 3: integrationhub.worker.v1.InvokeResponse
	nil,                    // 4: integrationhub.worker.v1.InvokeRequest.QueryEntry
	nil,                    // 5: integrationhub.worker.v1.InvokeRequest.HeadersEntry
}
var file_worker_proto_depIdxs = []int32{
	0, // 0: integrationhub.worker.v1.InvokeRequest.protocol:type_name -> integrationhub.worker.v1.Protocol
	4, // 1: integrationhub.worker.v1.InvokeRequest.query:type_name -> integrationhub.worker.v1.InvokeRequest.QueryEntry
	5, // 2: integrationhub.worker.v1.InvokeRequest.headers:type_name -> integrationhub.worker.v1.InvokeRequest.HeadersEntry
	1, // 3: integrationhub.worker.v1.InvokeRequest.emit:type_name -> integrationhub.worker.v1.Emit
	2, // 4: integrationhub.worker.v1.Worker.Invoke:input_type -> integrationhub.worker.v1.InvokeRequest
	3, // 5: integrationhub.worker.v1.Worker.Invoke:output_type -> integrationhub.worker.v1.InvokeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
